### ISSUE TITLE
Downloading Incorrect Subtitles

### ISSUE THREAD

**Issue by RafayGhafoor** [jodevsa/subscene_scraper#2]
The Script is downloading different subtitles for movies . For eg: When Searching for Black Mass, it downloads Captivate Movie Subtitles.

**Screenshot For Scraping Subtitles:-**
http://i.imgur.com/ehuI0Xu.png  (Scraping Fine)

**Screenshot For Incorrect Subtitles:**
If you look at the Parent Directories i.e The Movie Names and The Subtitles (*.srt) doesn't match.
http://i.imgur.com/Q6dApca.png

**Comment by jodevsa** [comment]
hello Rafay,

We are aware of this problem, sadly this is due to "subscene.com" search engine.
To get the whole picture, try manually searching for [Black.Mass.2015.720p.10bit.BlueRay...](https://subscene.com/subtitles/release?q=Black.Mass.2015.720p.10bit.BlueRay.2CH.x265);the first result is "Captive.2015.720p" and our script picks it .

**Comment by RafayGhafoor** [comment]
Thanks for your response jodevsa, i think this problem is solvable (But I am no JavaScript programmer so i am providing a solution below)
How about looping through the results and matching the search query with the output titles. For Eg: When it is searching for Black Mass 2016 etc you can use regular expression to get the year 2016 which would be like this: '\d{4}'. It would grab 2016 from black mass and then you can remove everything after 2016 so our name remaining would be like this:
From: Black.Mass.2016.HEVC.etc.Mkv
To: Black.Mass.2016 (Store it in a variable for eg: SearchTerm)

and then you can do a for loop.
for links in PAGE('a'):
 if SearchTerm in Title:
   getDownloadLink(fromPage)

**Comment by jodevsa** [comment]
surely this would work, but this would also eliminate search by release feature:
meta data written after movie name is important ; searching by release name  eliminates the need to sync subtitles with the movie.

Thanks,

**Comment by RafayGhafoor** [comment]
No man you don't get what i say (I think i am bad at explaining).
What i mean is this:

Suppose The Movie To Be Searched For is:-
Title = Black.Mass.2016.HEVC.Bluray.AAC.mp4
now when we search manually [TITLE] on site, the first link is of Captivate which is incorrect.

Now let's create a new variable in which we are going to replace '.' (period) with a blank space and anything after 2016 is removed let's name this variable:-

tempSearch = Black Mass 2016 # Temporary Search Variable!

now what we can do is that loop through all the links on the page and do this condition:
for links on Page:
    if tempSearch in TitleOfMovieOnPage:
        getlinkofMovie()
        break
    else:
       Keep Looping On the Page
       Continue

Now this will obviously work. To Sum this up, it will open the page of Black Mass Movie, Search in the first title which is Captivate. The Condition will be like this.
for links in page:
 if 'Black Mass' in 'Captivate':
  getLink()
  break  # This Condition will Return False because Black Mass != Captivate
 else:
  continue #It will keep looping and checking until the condition gets true

it has nothing to do with sync tbh.
