### ISSUE TITLE
Error: language not supported!

### ISSUE THREAD

**Issue by mognia** [jodevsa/subscene_scraper#8]
when i want download farsi (persian) subtitle sends me this err : Error: language not supported!

 subscene_scraper.passiveDownloader("La La Land",'farsi',path)
        .then(function(savedFiles){
            console.log('subtitle saved to ',savedFiles);
        })
        .catch(function(err){
            console.log('error:',err);
        });
}

**Comment by jodevsa** [comment]
hello @mmgh021 
use 'farsi/persian' for farsi (persian) subtitles 👍
